EXPERIMENT:
    run_name: billards
    experiment_dir: experiments
    overwrite: False
    load_run: False
    run_number: 0
    device: cuda
    log_every: 50
    seed: 0
    random_seed: False

MODULE:
    MONET:
        latent_dim: 8
        background_latent_dim: 1
        latent_prior: 1.0
        patch_shape:
        - 16
        - 16
        image_shape:
        - 64
        - 64
        bg_sigma: 0.01
        fg_sigma: 0.05
        num_blocks: 1
        channel_base: 8
        num_slots: 3
        beta: 1.0
        gamma: 0.1
        constrain_theta: False
        predict_masks: True
    STOVE:
        action_conditioned: True
        supairvised: False
        cl: 64
        debug_test_mode: False
        skip: 2
        debug_fix_supair: False
        debug_match_appearance: False
        debug_no_latents: False
    DYNAMICS:
        debug_nonlinear: 'relu'
        debug_latent_q_std: 0.04
        debug_xavier: False
        transition_lik_std:
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        pos_var: 0.3
        action_space: 9

TRAINING:
    optimizer:
        optimizer_name: Adam
        lr: 0.0001
    batch_size: 128
    epochs: 200
    reshape: False
    summarize: False
    parallel: True
    decay_rate: 0.9
    decay_schedule: 10
    clip_gradient: True
    clip_gradient_value: 10

DATA:
    data_name: billards
    data_dir: data/avoidance_train.pkl
    type: directory
    shape:
        - 64
        - 64
        - 3
    transform:
        - reshape
        - torch
