EXPERIMENT:
    game: DemonAttack-v0
    experiment: rl
    run_name: atari_test
    experiment_dir: experiments
    overwrite: False
    load_run: False
    run_number: 0
    device: cuda
    log_every: 50
    seed: 0
    random_seed: False
    pretrain_model: False
    pretrain_img: False
    algorithm: slac
RL:
  exploration_steps: 4
  action_force: 0.6
  eval_epochs: 100
  combined_nets: true
  use_stove: True
MODULE:
    SLAC:
        QNET:
        POLICY:
        rl_lr: 0.0003
        latent_lr: 0.0001
        update_steps_latent: 1
        update_steps_rl: 1
        update_target_steps: 1
        grad_clip_model: 20
        grad_clip_rl: 50
        initial_alpha: 0.05
        target_gamma: 0.999
        debug: False
        slac_latent_dim: 64
    DYNAMICS:
        action_space: 6
        debug_latent_q_std: 0.04
        debug_nonlinear: relu
        debug_xavier: false
        num_dynamics: 2
        pos_var: 0.3
        transition_lik_std:
        - 0.01
        - 0.01
        - 0.01
        - 0.01
    MONET:
        background_latent_dim: 1
        beta: 1.0
        bg_sigma: 0.01
        channel_base: 8
        constrain_theta: true
        fg_sigma: 0.05
        gamma: 0.1
        image_shape:
        - 64
        - 64
        latent_dim: 8
        latent_prior: 1.0
        max_obj_size: 0.2
        num_blocks: 2
        num_slots: 8
        patch_shape:
        - 16
        - 16
        predict_masks: false
    STOVE:
        action_conditioned: true
        cl: 128
        debug_fix_supair: true
        debug_match_appearance: false
        debug_no_latents: false
        debug_test_mode: false
        dyn_recon_weight: 0.0
        skip: 2
        supairvised: false
TRAINING:
    optimizer:
        optimizer_name: Adam
        lr: 0.0003
    batch_size: 256
    epochs: 10
    reshape: False
    summarize: False
    parallel: True
    decay_rate: 0.99
    decay_schedule: 1
    clip_gradient: True
    clip_gradient_value: 20
    pretrain: True
    rl_batch_size: 64
    total_steps: 100000
DATA:
    data_name: billards
    data_dir: data/avoidance_train.pkl
    type: directory
    shape:
        - 128
        - 128
        - 3
    transform:
        - reshape
        - torch
