EXPERIMENT:
    run_name: atari
    game: DemonAttack-v0
    experiment_dir: experiments
    overwrite: False
    load_run: False
    run_number: 0
    device: cuda
    log_every: 50

MODULE:
  latent_dim: 32
  latent_prior: 1.0
  patch_shape: 
  - 16
  - 16
  image_shape: 
  - 128
  - 128
  bg_sigma: 0.01
  fg_sigma: 0.05
  num_blocks: 2
  channel_base: 8
  num_slots: 6
  beta: 1.0
  gamma: 0.1
  constrain_theta: False
  predict_masks: false

TRAINING:
    optimizer:
        optimizer_name: Adam
        lr: 0.0001
    batch_size: 64
    epochs: 50
    reshape: False
    summarize: False
    parallel: True
    clip_gradient: True
    clip_gradient_value: 20

DATA:
    data_name: billards
    data_dir: test_atari
    type: directory
    shape:
        - 128
        - 128
        - 3
    transform:
        - reshape
        - torch
