EXPERIMENT:
    run_name: billards
    experiment_dir: experiments
    overwrite: False
    load_run: False
    run_number: 0
    device: cuda
    log_every: 250

MODULE:
    latent_dim: 64
    background_latent_dim: 1
    latent_prior: 1.0
    patch_shape:
    - 16
    - 16
    image_shape:
    - 64
    - 64
    bg_sigma: 0.01
    fg_sigma: 0.05
    num_blocks: 2
    channel_base: 8
    num_slots: 8
    beta: 1.0
    gamma: 1.0
    constrain_theta: False

TRAINING:
    optimizer:
        optimizer_name: Adam
        lr: 0.0007
    batch_size: 64
    epochs: 100
    reshape: False
    summarize: False
    parallel: True

DATA:
    data_name: billards
    data_dir: test_billards
    type: directory
    shape:
        - 64
        - 64
        - 3
    transform:
        - reshape
        - torch
